DROP TABLE question CASCADE;
DROP TABLE disease CASCADE;
DROP TABLE meal CASCADE;
DROP TABLE verification CASCADE;
DROP TABLE conclusion CASCADE;
DROP TABLE method CASCADE;
DROP TABLE human CASCADE;
DROP TYPE DISEASE_PAIN_LEVEL;
