DROP TABLE question CASCADE;
DROP TABLE disease CASCADE;
DROP TABLE meal CASCADE;
DROP TABLE verification CASCADE;
DROP TABLE conclusion CASCADE;
DROP TABLE object CASCADE;
DROP TABLE human CASCADE;
DROP TABLE method CASCADE;
